#!/usr/bin/env python3
"""Write the business details Google reads (schema.org JSON-LD) into every page.

Google shows the business name, hours, service area and Business Profile link in
search results from this block, so it has to say the same thing on every page and
match the Google Business Profile. Edit BUSINESS below, then run:

    python3 tools/make-structured-data.py

Each page gets the business itself, a description of that page, and (except the
home page) a breadcrumb trail. The block sits just before </body>, between the
STRUCTURED DATA markers, and is replaced wholesale on every run.
"""

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://gabrielaprojects.com"
PROFILE = "https://www.google.com/maps/place/?q=place_id:ChIJV9o5SZi7KCYRHaxZRhk0vlA"

# Keep in step with the Google Business Profile (hours, towns, phone).
BUSINESS = {
    "@type": "HomeAndConstructionBusiness",
    "@id": f"{SITE}/#business",
    "name": "Gabriela Projects",
    "description": "Woman-owned design-build firm based in Glen Ridge, New Jersey, serving Essex County "
                   "and New York City, specializing in full renovations, custom millwork and construction.",
    "url": f"{SITE}/",
    "telephone": "+1-862-402-2031",
    "email": "info@gabrielaprojects.com",
    "logo": f"{SITE}/images/common/logo.svg",
    "image": f"{SITE}/images/common/og-home.jpg",
    "priceRange": "$$$$",
    "address": {
        "@type": "PostalAddress",
        "addressLocality": "Glen Ridge",
        "addressRegion": "NJ",
        "postalCode": "07028",
        "addressCountry": "US",
    },
    "hasMap": PROFILE,
    "sameAs": ["https://www.instagram.com/gabrielaprojects/", PROFILE],
    "openingHoursSpecification": [{
        "@type": "OpeningHoursSpecification",
        "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        "opens": "09:00",
        "closes": "17:00",
    }],
    "founder": {"@type": "Person", "name": "Gabriela Flores"},
    "areaServed": [
        *({"@type": "City", "name": f"{town}, NJ"} for town in (
            "Glen Ridge", "Montclair", "Bloomfield", "West Orange", "Nutley", "Verona",
            "Cedar Grove", "Caldwell", "Maplewood", "South Orange", "Livingston", "Belleville")),
        {"@type": "AdministrativeArea", "name": "Essex County, New Jersey"},
        {"@type": "City", "name": "New York, NY"},
    ],
    "knowsAbout": ["Custom Millwork", "Renovations", "Interior Design", "Construction",
                   "Kitchen Remodeling", "Bathroom Remodeling", "Co-op Renovations",
                   "Historic Home Renovation"],
}

# page file -> (URL path, breadcrumb name or None for no breadcrumb)
PAGES = {
    "index.html": ("/", None),
    "services.html": ("/services", "Services"),
    "how-it-works.html": ("/how-it-works", "How It Works"),
    "portfolio.html": ("/portfolio", "Portfolio"),
    "get-started.html": ("/get-started", "Get Started"),
    "hello.html": ("/hello", None),
}

START = "<!-- STRUCTURED DATA: generated by tools/make-structured-data.py, edit that script instead -->"
END = "<!-- /STRUCTURED DATA -->"


def graph(path, crumb, title):
    url = SITE + path
    page = {
        "@type": "WebPage",
        "@id": f"{url}#webpage",
        "url": url,
        "name": title,
        "isPartOf": {"@id": f"{SITE}/#website"},
        "about": {"@id": f"{SITE}/#business"},
    }
    nodes = [BUSINESS, page]
    if path == "/":
        nodes.append({
            "@type": "WebSite",
            "@id": f"{SITE}/#website",
            "url": f"{SITE}/",
            "name": "Gabriela Projects",
            "publisher": {"@id": f"{SITE}/#business"},
        })
    if crumb:
        page["breadcrumb"] = {"@id": f"{url}#breadcrumb"}
        nodes.append({
            "@type": "BreadcrumbList",
            "@id": f"{url}#breadcrumb",
            "itemListElement": [
                {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
                {"@type": "ListItem", "position": 2, "name": crumb, "item": url},
            ],
        })
    return {"@context": "https://schema.org", "@graph": nodes}


def main():
    for name, (path, crumb) in PAGES.items():
        file = os.path.join(ROOT, name)
        html = open(file, encoding="utf-8").read()
        title = re.search(r"<title>(.*?)</title>", html, re.S).group(1).replace("&amp;", "&").strip()
        body = json.dumps(graph(path, crumb, title), indent=2, ensure_ascii=False)
        block = f'{START}\n  <script type="application/ld+json">\n{body}\n  </script>\n  {END}'
        if START in html:
            html = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, html, flags=re.S)
        else:
            html = html.replace("</body>", f"  {block}\n</body>", 1)
        open(file, "w", encoding="utf-8").write(html)
        print(f"{name}: {path}" + (f" (breadcrumb: Home > {crumb})" if crumb else ""))


if __name__ == "__main__":
    main()
